name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/antonbabenko/pre-commit-terraform:latest
      volumes:
        - ${{ github.workspace }}:/lint
      options: -w /lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run pre-commit
        run: |
          pre-commit run -a
